name: XCTest

on:
  push:
    branches:
        - main
        - develop

jobs:
  test-ios:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests on iPhone14
      run: xcodebuild test -destination 'name=iPhone 14' -scheme 'MightyCombine-Package'
