name: XCTest

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: xcodebuild test -scheme 'MightyCombine-Package'
