# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
        - "*"

jobs:
  build:

    runs-on: macos-latest

#    steps:
#    - uses: actions/checkout@v3
#    - name: Build
#      run: swift build -v
#    - name: Run tests
#      run: swift test -v

    steps:
    
      - name: Repository checkout
        uses: actions/checkout@v2
        
      - name: Build for iOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme MightyCombine -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
      - name: Run iOS tests
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme MightyCombine -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
        
      - name: Build for iOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme MightySwift -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
      - name: Run iOS tests
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild test-without-building -scheme MightySwift -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
    
#      - uses: actions/checkout@v4
#      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
#        with:
#          swift-version: "5.4"
#      - name: Build
#        run: swift build
#      - name: Run tests
#        run: swift test
